### ISSUE TITLE
Network error: API problem which results in app not working

### ISSUE THREAD

**Issue by tohrxyz** [Wilson-Wu1/AaveLiquidationCalculator#1]
Hey there, for the past few weeks I've been noticing that this app doesn't work no more.

I've noticed in network tab that api calls to `https://api.thegraph.com/subgraphs/name/aave/protocol-v3` are failing due to 410 Gone.

Also console errors about cors, but i think the underlying problem is the change of api server.

**Comment by JO-OLADEJI** [comment]
Heyy @tohrxyz - been seeing this error for the past few weeks as well. Just cloned the repo now and I've fixed the issue. I'll create a PR in a few minutes so when @Wilson-Wu1 merges it, the website will be up and running 🤝

**Comment by JO-OLADEJI** [comment]
@Wilson-Wu1 I think this issue can be closed now
